name: Telegram Backtest Trigger

on:
  schedule:
    - cron: "*/5 * * * *"

  workflow_dispatch:

jobs:
  telegram-trigger:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install requests
        run: |
          pip install requests

      - name: Check Telegram Commands
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          GITHUB_OWNER: bj73581028
          GITHUB_REPO: cindy_tw_stock_radar_bot
        run: |
          python telegram_trigger.py
